//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAsignacionMaquinariaBLL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asi_Maquinaria
    {
        public int maqId { get; set; }
        public string maqSerie { get; set; }
        public string maqDescripcion { get; set; }
        public Nullable<bool> maqEstado { get; set; }
        public Nullable<System.DateTime> maqFechaCreacion { get; set; }
        public Nullable<int> empId { get; set; }
        public Nullable<bool> maqDisponible { get; set; }
    
        public virtual Asi_Empleado Asi_Empleado { get; set; }
    }
}
