//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAsignacionMaquinariaBLL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AsignacionMaquinariaDBEntities : DbContext
    {
        public AsignacionMaquinariaDBEntities()
            : base("name=AsignacionMaquinariaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asi_Empleado> Asi_Empleado { get; set; }
        public virtual DbSet<Asi_Maquinaria> Asi_Maquinaria { get; set; }
    }
}
